### ISSUE TITLE
undefined method `quiet_input' after update to 1.1.0

### ISSUE THREAD

**Issue by mjthompsgb** [NUARIG/surveyor#388]
Getting the below error when trying to start a survey after updating the Surveyor Gem. Before this error I was getting permission errors on 1 CSS and 1 JS file. I chmod'ed them and then was able to get the list of Surveys to come up but when I attempt to take one I get this error. I tried updating Formtastic but was already at version 2.1.1.

---

Showing /apps/rfq.wspg.com/app/views/partials/_answer.html.haml where line #7 raised:

undefined method `quiet_input' for #Formtastic::FormBuilder:0x007f3db9b27728
Extracted source (around line #7):

4: - i = response_idx(q.pick != "one") # argument will be false (don't increment i) if we're on radio buttons
5: - disabled = defined?(disableFlag) ? disableFlag : false
6: = f.semantic_fields_for i, r do |ff|
7:   = ff.quiet_input :question_id unless q.pick == "one" # don't repeat question_id if we're on radio buttons
8:   = ff.quiet_input :id unless q.pick == "one" or r.new_record?
9:   = ff.quiet_input :response_group, :value => rg if q.pick != "one" && g && g.display_type == "repeater"
10:   - case q.pick

---

Any ideas would be awesome.
Thanks
Matt

**Comment by yoon** [comment]
I believe this is a result of not running `rails generate surveyor:install after upgrading`. The view partials have been updated.

**Comment by mjthompsgb** [comment]
Thanks for the super quick response. I did run script/rails generate surveyor:install after the update and then migrated the database. And I just tried running it again the way you said but it didn't make any difference.

I did notice right before your response that it is for some reason still trying to use the partials from the old version of Surveyor. Any idea how to force it to look in the right spot and get the new ones?

**Comment by yoon** [comment]
Two possible solutions: are you using bundler to ensure that the right
version of the gem in being used? Do you have some customized or old
surveyor partials in your app directory?

Mark A. Wimbiscus Yoon
Northwestern University Clinical and Translational Sciences Institute
(NUCATS)
yoon@northwestern.edu
http://www.nucats.northwestern.edu

**Comment by mjthompsgb** [comment]
You Rock!

Thanks again for the quick response. I forget that I did move the partials to my app but never did any customizing. For some reason I was not paying attention to the fact that the error said the actual path to the partials directory in my app. I made the changes in them and now it works fine.

Sorry to bother you when I should have been able to figure it out.
Thanks 
Matt

**Comment by yoon** [comment]
Take care, thanks for using surveyor!

Mark A. Wimbiscus Yoon
Northwestern University Clinical and Translational Sciences Institute
(NUCATS)
yoon@northwestern.edu
http://www.nucats.northwestern.edu
